#!/usr/bin/env python3

# version: 1.2

"""
asset_cleanup.py
Removes Kometa asset folders/files that have no matching entry in
Radarr (TMDB), Sonarr (TVDB), or Plex collections.

Config: asset_cleanup.yml (same directory as this script)
"""

import os
import re
import sys
import shutil
import logging
import argparse
from pathlib import Path
from datetime import datetime

import requests
import yaml

# ─── Logging ────────────────────────────────────────────────────────────────

# Colours are disabled automatically when stdout is not a TTY
# (e.g. Unraid User Scripts output window).
_IS_TTY = sys.stdout.isatty()

RESET  = "\033[0m"  if _IS_TTY else ""
BOLD   = "\033[1m"  if _IS_TTY else ""
RED    = "\033[91m" if _IS_TTY else ""
GREEN  = "\033[92m" if _IS_TTY else ""
YELLOW = "\033[93m" if _IS_TTY else ""
CYAN   = "\033[96m" if _IS_TTY else ""
DIM    = "\033[2m"  if _IS_TTY else ""


class ColourFormatter(logging.Formatter):
    COLOURS = {
        logging.DEBUG:    DIM,
        logging.INFO:     RESET,
        logging.WARNING:  YELLOW,
        logging.ERROR:    RED,
        logging.CRITICAL: RED + BOLD,
    }

    def format(self, record):
        colour = self.COLOURS.get(record.levelno, RESET)
        msg = super().format(record)
        return f"{colour}{msg}{RESET}" if _IS_TTY else msg


def setup_logging(verbose: bool = False) -> logging.Logger:
    logger = logging.getLogger("asset_cleanup")
    logger.setLevel(logging.DEBUG if verbose else logging.INFO)
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(ColourFormatter(
        "%(asctime)s  %(levelname)-8s  %(message)s", datefmt="%H:%M:%S"
    ))
    logger.addHandler(handler)
    return logger


log = setup_logging()

# ─── Config ─────────────────────────────────────────────────────────────────

SCRIPT_DIR  = Path(__file__).parent
CONFIG_PATH = SCRIPT_DIR / "asset_cleanup.yml"

DEFAULT_CONFIG = {
    "dry_run": True,
    "delete_unknown": False,
    "verbose": False,
    # List primary asset dirs only — tmp subdirs are checked automatically.
    "asset_dirs": [
        "/mnt/user/appdata/kometa/assets",
    ],
    "radarr": [{"name": "Radarr", "url": "http://localhost:7878", "api_key": "YOUR_RADARR_API_KEY"}],
    "sonarr": [{"name": "Sonarr", "url": "http://localhost:8989", "api_key": "YOUR_SONARR_API_KEY"}],
    "plex":   {"url": "http://localhost:32400", "token": "YOUR_PLEX_TOKEN"},
    "discord": {"webhook_url": "", "notify_on_dry_run": True},
}


def load_config() -> dict:
    if not CONFIG_PATH.exists():
        log.warning(f"Config not found at {CONFIG_PATH}, writing defaults.")
        with open(CONFIG_PATH, "w") as f:
            yaml.dump(DEFAULT_CONFIG, f, default_flow_style=False, sort_keys=False)
        log.error("Please edit the config file and re-run.")
        sys.exit(1)
    with open(CONFIG_PATH) as f:
        cfg = yaml.safe_load(f)
    for key, val in DEFAULT_CONFIG.items():
        cfg.setdefault(key, val)
    return cfg

# ─── Helpers ────────────────────────────────────────────────────────────────

def _normalise_name(name: str) -> str:
    """Lowercase, collapse whitespace, strip punctuation for fuzzy matching.
    Normalises '&' to 'and' before stripping punctuation so that folder names
    generated by Kometa (which spells out 'and') match Sonarr/Radarr titles
    that use '&' (e.g. 'Law & Order' vs 'Law and Order').
    """
    name = name.lower()
    name = re.sub(r"&", "and", name)        # & → and before punctuation strip
    name = re.sub(r"[^\w\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def _entry_size(path: Path) -> str:
    """Human-readable size of a file or directory."""
    try:
        if path.is_dir():
            total = sum(f.stat().st_size for f in path.rglob("*") if f.is_file())
        else:
            total = path.stat().st_size
        for unit in ("B", "KB", "MB", "GB"):
            if total < 1024:
                return f"{total:.0f} {unit}"
            total /= 1024
        return f"{total:.1f} TB"
    except Exception:
        return "?"

# ─── API helpers ────────────────────────────────────────────────────────────

def _normalise_instances(cfg_value) -> list[dict]:
    """Accept either a single instance dict or a list of instance dicts."""
    if isinstance(cfg_value, dict):
        return [cfg_value]
    return cfg_value or []


def get_radarr_data(instances: list[dict]) -> tuple[set[int], set[str]]:
    """Return combined (tmdb_ids, normalised_titles) across all Radarr instances."""
    all_ids:    set[int] = set()
    all_titles: set[str] = set()
    for inst in instances:
        name    = inst.get("name", inst["url"])
        resp    = requests.get(
            f"{inst['url'].rstrip('/')}/api/v3/movie",
            headers={"X-Api-Key": inst["api_key"]},
            timeout=30,
        )
        resp.raise_for_status()
        movies = resp.json()
        ids    = {m["tmdbId"] for m in movies if m.get("tmdbId")}
        titles = {_normalise_name(m["title"]) for m in movies if m.get("title")}
        all_ids    |= ids
        all_titles |= titles
        log.info(f"Radarr [{name}]: {len(ids):,} movies loaded")
    return all_ids, all_titles


def get_sonarr_data(instances: list[dict]) -> tuple[set[int], set[str]]:
    """Return combined (tvdb_ids, normalised_titles) across all Sonarr instances."""
    all_ids:    set[int] = set()
    all_titles: set[str] = set()
    for inst in instances:
        name = inst.get("name", inst["url"])
        resp = requests.get(
            f"{inst['url'].rstrip('/')}/api/v3/series",
            headers={"X-Api-Key": inst["api_key"]},
            timeout=30,
        )
        resp.raise_for_status()
        series = resp.json()
        ids    = {s["tvdbId"] for s in series if s.get("tvdbId")}
        titles = {_normalise_name(s["title"]) for s in series if s.get("title")}
        all_ids    |= ids
        all_titles |= titles
        log.info(f"Sonarr [{name}]: {len(ids):,} series loaded")
    return all_ids, all_titles


def get_plex_collection_names(url: str, token: str) -> set[str]:
    """Return a normalised set of all collection names across all libraries."""
    base    = url.rstrip("/")
    headers = {"X-Plex-Token": token, "Accept": "application/json"}

    resp = requests.get(f"{base}/library/sections", headers=headers, timeout=30)
    resp.raise_for_status()
    sections = resp.json()["MediaContainer"].get("Directory", [])

    names: set[str] = set()
    for section in sections:
        key  = section["key"]
        resp = requests.get(
            f"{base}/library/sections/{key}/collections",
            headers=headers,
            timeout=30,
        )
        resp.raise_for_status()
        for col in resp.json()["MediaContainer"].get("Metadata", []):
            title = col.get("title", "").strip()
            if title:
                names.add(_normalise_name(title))

    log.info(f"Plex: {len(names):,} collections loaded")
    return names

# ─── Asset scanning ─────────────────────────────────────────────────────────

# Numeric ID tags  →  {tmdb-12345}  /  {tvdb-12345}
RE_TMDB = re.compile(r"\{tmdb-(\d+)\}", re.IGNORECASE)
RE_TVDB = re.compile(r"\{tvdb-(\d+)\}", re.IGNORECASE)

# Unresolved Kometa placeholders  →  {tmdb-{TmdbId}}  /  {tvdb-{TvdbId}}
RE_TMDB_UNRESOLVED = re.compile(r"\{tmdb-\{[^}]+\}\}", re.IGNORECASE)
RE_TVDB_UNRESOLVED = re.compile(r"\{tvdb-\{[^}]+\}\}", re.IGNORECASE)

# Extract bare title (everything before the year bracket or tag)
RE_TITLE = re.compile(r"^(.+?)(?:\s*\(\d{4}\)|\s*\{)", re.IGNORECASE)


def _extract_title(name: str) -> str:
    """Pull the bare title out of a folder name, normalised."""
    m = RE_TITLE.match(name)
    return _normalise_name(m.group(1) if m else name)


def classify_entry(name: str) -> tuple[str, int | None]:
    """
    Returns one of:
      ('tmdb', id)              — resolved TMDB ID
      ('tvdb', id)              — resolved TVDB ID
      ('tmdb_unresolved', None) — Kometa placeholder {tmdb-{TmdbId}}
      ('tvdb_unresolved', None) — Kometa placeholder {tvdb-{TvdbId}}
      ('collection', None)      — no ID tag at all
    """
    m = RE_TMDB.search(name)
    if m:
        return "tmdb", int(m.group(1))
    m = RE_TVDB.search(name)
    if m:
        return "tvdb", int(m.group(1))
    if RE_TMDB_UNRESOLVED.search(name):
        return "tmdb_unresolved", None
    if RE_TVDB_UNRESOLVED.search(name):
        return "tvdb_unresolved", None
    return "collection", None


def build_ignore_set(ignore_list: list[str]) -> set[str]:
    """Normalise the ignore list from config for consistent matching."""
    return {_normalise_name(name) for name in ignore_list if name}


def scan_asset_dir(
    directory: Path,
    skip_dirs: set[Path],
    radarr_ids: set[int],
    radarr_titles: set[str],
    sonarr_ids: set[int],
    sonarr_titles: set[str],
    plex_names: set[str],
    ignore_set: set[str],
) -> tuple[list[Path], list[Path], list[Path], list[Path]]:
    """
    Scan one asset directory (top level only).

    Matching priority per entry:
      1. Ignore list → silently kept
      2. Resolved ID tag → matched against Radarr/Sonarr by ID
      3. ID not found → title fallback against Radarr/Sonarr titles
      4. Unresolved placeholder ({tvdb-{TvdbId}}) → title fallback
      5. No ID tag → matched against Plex collections by name
      6. Nothing matched → unknown (kept + warned, or deleted if delete_unknown)

    Returns (keep, remove, unknown, ignored).
    """
    keep:    list[Path] = []
    remove:  list[Path] = []
    unknown: list[Path] = []
    ignored: list[Path] = []

    if not directory.exists():
        log.warning(f"Asset dir not found, skipping: {directory}")
        return keep, remove, unknown, ignored

    for entry in sorted(directory.iterdir()):
        name = entry.name

        # Skip subdirectories that are themselves scanned as asset_dirs
        if entry.is_dir() and entry.resolve() in skip_dirs:
            log.debug(f"  Skipping nested scan dir: {name}")
            continue

        # ── 1. Ignore list ───────────────────────────────────────────────────
        name_stem = Path(name).stem if entry.is_file() else name
        if _normalise_name(name_stem) in ignore_set:
            ignored.append(entry)
            log.debug(f"  Ignored (config): {name}")
            continue

        kind, eid = classify_entry(name)
        title = _extract_title(name)

        if kind == "tmdb":
            # ── 2. Resolved TMDB ID ──────────────────────────────────────────
            if eid in radarr_ids:
                keep.append(entry)
            # ── 3. ID miss → title fallback ──────────────────────────────────
            elif title in radarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Radarr): {name}")
            else:
                remove.append(entry)

        elif kind == "tvdb":
            # ── 2. Resolved TVDB ID ──────────────────────────────────────────
            if eid in sonarr_ids:
                keep.append(entry)
            # ── 3. ID miss → title fallback ──────────────────────────────────
            elif title in sonarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Sonarr): {name}")
            else:
                remove.append(entry)

        elif kind == "tmdb_unresolved":
            # ── 4. Unresolved placeholder → title fallback ───────────────────
            if title in radarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Radarr, unresolved ID): {name}")
            else:
                unknown.append(entry)

        elif kind == "tvdb_unresolved":
            # ── 4. Unresolved placeholder → title fallback ───────────────────
            if title in sonarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Sonarr, unresolved ID): {name}")
            else:
                unknown.append(entry)

        else:
            # ── 5. No ID tag → Plex collection, then Sonarr/Radarr title ─────
            normalised = _normalise_name(name)
            if normalised in plex_names:
                keep.append(entry)
            elif title in sonarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Sonarr, no ID tag): {name}")
            elif title in radarr_titles:
                keep.append(entry)
                log.debug(f"  Kept by title fallback (Radarr, no ID tag): {name}")
            else:
                unknown.append(entry)

    return keep, remove, unknown, ignored


def find_tmp_companion(path: Path) -> Path | None:
    """
    Return the matching entry in the sibling tmp/ dir if it exists,
    otherwise None.  e.g. assets/Show (2024)/ → assets/tmp/Show (2024)/
    """
    companion = path.parent / "tmp" / path.name
    return companion if companion.exists() else None

# ─── Deletion ────────────────────────────────────────────────────────────────

def delete_entry(path: Path, dry_run: bool) -> bool:
    """Delete a file or directory tree. Returns True on success."""
    try:
        if not dry_run:
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
                # Remove parent folder if it is now empty
                parent = path.parent
                if parent.exists() and not any(parent.iterdir()):
                    parent.rmdir()
                    log.debug(f"Removed empty parent: {parent}")
        return True
    except Exception as exc:
        log.error(f"Failed to delete {path}: {exc}")
        return False


def sweep_empty_dirs(asset_dirs: list[Path], skip_dirs: set[Path], dry_run: bool) -> int:
    """
    Walk all asset dirs bottom-up and remove any empty directories,
    skipping dirs that are themselves configured scan targets.
    Returns count of removed dirs.
    """
    removed = 0
    for asset_dir in asset_dirs:
        if not asset_dir.exists():
            continue
        for root, dirs, files in os.walk(asset_dir, topdown=False):
            for dir_name in dirs:
                dir_path = Path(root) / dir_name
                if dir_path.resolve() in skip_dirs:
                    continue
                try:
                    if not any(dir_path.iterdir()):
                        log.info(f"  Removing empty folder: {dir_path.name}")
                        if not dry_run:
                            dir_path.rmdir()
                        removed += 1
                except Exception as exc:
                    log.error(f"Failed to remove empty folder {dir_path}: {exc}")
    return removed

# ─── Discord ─────────────────────────────────────────────────────────────────

def send_discord(
    webhook_url: str,
    dry_run: bool,
    delete_unknown: bool,
    per_dir: list[dict],
    all_remove: list[Path],
    all_unknown: list[Path],
) -> None:
    if not webhook_url:
        return

    mode   = "🔍 DRY RUN" if dry_run else "🗑️ CLEANUP"
    colour = 0xF4A460 if dry_run else 0xE74C3C
    action = "Would remove" if dry_run else "Removed"

    def _bullet_list(paths: list[Path], limit: int) -> str:
        lines = [f"• {p.name}" for p in paths[:limit]]
        if len(paths) > limit:
            lines.append(f"… and {len(paths) - limit} more")
        return "\n".join(lines) or "—"

    unknown_label = (
        "would remove" if delete_unknown and dry_run
        else "removed" if delete_unknown
        else "kept"
    )

    fields = [
        {"name": f"{action} (orphaned)", "value": str(len(all_remove)), "inline": True},
        {"name": f"⚠️ Unknown ({unknown_label})", "value": str(len(all_unknown)), "inline": True},
    ]

    for d in per_dir:
        removed  = d["remove"]
        unknown  = d["unknown"]
        tmp_companions = d.get("tmp_companions", [])
        if not removed and not unknown:
            continue
        lines = []
        for p in removed[:10]:
            suffix = " + tmp" if any(c.name == p.name for c in tmp_companions) else ""
            lines.append(f"✗ {p.name}{suffix}")
        for p in (unknown if delete_unknown else [])[:5]:
            lines.append(f"✗ {p.name} (unknown)")
        for p in (unknown if not delete_unknown else [])[:5]:
            lines.append(f"? {p.name} (unknown)")
        extra = max(0, len(removed) - 10) + max(0, len(unknown) - 5)
        if extra:
            lines.append(f"… and {extra} more")
        if lines:
            fields.append({
                "name": f"📁 [{d['label']}]",
                "value": "\n".join(lines),
                "inline": False,
            })

    payload = {
        "embeds": [{
            "title": f"Asset Cleanup  {mode}",
            "color": colour,
            "fields": fields,
            "footer": {"text": datetime.now().strftime("%Y-%m-%d %H:%M")},
        }]
    }
    try:
        r = requests.post(webhook_url, json=payload, timeout=10)
        r.raise_for_status()
    except Exception as exc:
        log.warning(f"Discord notification failed: {exc}")

# ─── Main ────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Remove orphaned Kometa asset folders.")
    parser.add_argument("--dry-run",    action="store_true",
                        help="Show what would be removed (default from config).")
    parser.add_argument("--no-dry-run", dest="dry_run", action="store_false",
                        help="Actually delete orphaned assets.")
    parser.add_argument("--delete-unknown", dest="delete_unknown", action="store_true",
                        default=None,
                        help="Also delete unknown entries (no ID tag, not in Plex).")
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.set_defaults(dry_run=None, delete_unknown=None)
    args = parser.parse_args()

    cfg            = load_config()
    dry_run        = cfg.get("dry_run", True)        if args.dry_run        is None else args.dry_run
    delete_unknown = cfg.get("delete_unknown", False) if args.delete_unknown is None else args.delete_unknown
    verbose        = cfg.get("verbose", False) or args.verbose

    if verbose:
        log.setLevel(logging.DEBUG)

    # ── Banner ──────────────────────────────────────────────────────────────
    mode_label    = f"{YELLOW}{BOLD}DRY RUN{RESET}" if dry_run else f"{RED}{BOLD}LIVE MODE — files will be deleted{RESET}"
    unknown_label = f"  {YELLOW}(+unknown entries){RESET}" if delete_unknown else ""
    print(f"\n{CYAN}{BOLD}{'─'*60}{RESET}")
    print(f"{CYAN}{BOLD}  Asset Cleanup{RESET}  {mode_label}{unknown_label}")
    print(f"{CYAN}{BOLD}{'─'*60}{RESET}\n")

    # ── Fetch API data ───────────────────────────────────────────────────────
    log.info("Fetching data from Radarr, Sonarr and Plex …")
    try:
        radarr_ids, radarr_titles = get_radarr_data(_normalise_instances(cfg.get("radarr", [])))
        sonarr_ids, sonarr_titles = get_sonarr_data(_normalise_instances(cfg.get("sonarr", [])))
        plex_names                = get_plex_collection_names(cfg["plex"]["url"], cfg["plex"]["token"])
    except requests.RequestException as exc:
        log.error(f"API error: {exc}")
        sys.exit(1)

    print()

    # ── Ignore list ──────────────────────────────────────────────────────────
    ignore_set = build_ignore_set(cfg.get("ignore") or [])
    if ignore_set:
        log.info(f"Ignoring {len(ignore_set)} entries from config")

    # ── Asset dirs ───────────────────────────────────────────────────────────
    asset_dirs = [Path(d) for d in cfg.get("asset_dirs", [])]
    skip_dirs  = {d.resolve() for d in asset_dirs}
    skip_dirs |= {(d / "tmp").resolve() for d in asset_dirs if (d / "tmp").exists()}

    # ── Scan & report per directory ──────────────────────────────────────────
    all_keep:    list[Path] = []
    all_remove:  list[Path] = []
    all_unknown: list[Path] = []
    all_ignored: list[Path] = []
    per_dir:     list[dict] = []

    for asset_dir in asset_dirs:
        log.info(f"Scanning {asset_dir} …")

        keep, remove, unknown, ignored = scan_asset_dir(
            asset_dir, skip_dirs,
            radarr_ids, radarr_titles,
            sonarr_ids, sonarr_titles,
            plex_names, ignore_set,
        )

        # ── tmp deduplication ────────────────────────────────────────────────
        # For every removal candidate, check if a matching entry exists in the
        # sibling tmp/ dir and queue it alongside — avoids scanning tmp
        # separately and reporting the same entry twice.
        tmp_companions: list[Path] = []
        for path in remove + (unknown if delete_unknown else []):
            companion = find_tmp_companion(path)
            if companion and companion not in tmp_companions:
                tmp_companions.append(companion)
                log.debug(f"  Found tmp companion: {companion.name}")

        all_keep    += keep
        all_remove  += remove + tmp_companions
        all_unknown += unknown
        all_ignored += ignored
        per_dir.append({
            "label": asset_dir.name,
            "remove": remove,
            "unknown": unknown,
            "tmp_companions": tmp_companions,
        })

        log.info(
            f"  {GREEN}Keep: {len(keep)}{RESET}  "
            f"{RED}Remove: {len(remove)}{RESET}"
            + (f" (+{len(tmp_companions)} tmp){RESET}" if tmp_companions else "") +
            f"  {YELLOW}Unknown: {len(unknown)}{RESET}"
            + (f"  {DIM}Ignored: {len(ignored)}{RESET}" if ignored else "")
        )

        # Report removals
        if remove:
            label = "Would remove" if dry_run else "Removing"
            log.info(f"  {label} {len(remove)} orphaned entries"
                     + (f" + {len(tmp_companions)} tmp companions:" if tmp_companions else ":"))
            for path in sorted(remove, key=lambda p: p.name.lower()):
                has_companion = any(c.name == path.name for c in tmp_companions)
                companion_tag = f"  {DIM}[+tmp]{RESET}" if has_companion else ""
                log.info(f"    {RED}✗ {path.name}  {DIM}({_entry_size(path)}){RESET}{companion_tag}")
        else:
            log.info(f"  {GREEN}No orphaned entries.{RESET}")

        # Report unknowns
        if unknown:
            if delete_unknown:
                label_u = "Would remove" if dry_run else "Removing"
                log.info(f"  {label_u} {len(unknown)} unknown entries (no ID tag, not in Plex):")
                for path in sorted(unknown, key=lambda p: p.name.lower()):
                    log.info(f"    {RED}✗ {path.name}  {DIM}({_entry_size(path)}){RESET}")
            else:
                log.warning(f"  {len(unknown)} entries have no ID tag and are not in Plex — review manually:")
                for path in sorted(unknown, key=lambda p: p.name.lower()):
                    log.warning(f"    {YELLOW}? {path.name}{RESET}")

        print()

    # ── Execute deletions ────────────────────────────────────────────────────
    deleted = 0
    failed  = 0
    for path in all_remove:
        if delete_entry(path, dry_run):
            deleted += 1
            if not dry_run:
                log.debug(f"Deleted: {path}")
        else:
            failed += 1

    # ── Execute unknown deletions ────────────────────────────────────────────
    deleted_unknown = 0
    failed_unknown  = 0
    if delete_unknown:
        for path in all_unknown:
            if delete_entry(path, dry_run):
                deleted_unknown += 1
                if not dry_run:
                    log.debug(f"Deleted unknown: {path}")
            else:
                failed_unknown += 1

    # ── Empty folder sweep ───────────────────────────────────────────────────
    if not dry_run:
        swept = sweep_empty_dirs(asset_dirs, skip_dirs, dry_run=False)
        if swept:
            log.info(f"Swept {swept} empty folder(s)")
    else:
        # Report what would be swept without touching anything
        swept = sweep_empty_dirs(asset_dirs, skip_dirs, dry_run=True)
        if swept:
            log.info(f"Would sweep {swept} empty folder(s)")

    # ── Summary ──────────────────────────────────────────────────────────────
    print(f"\n{CYAN}{BOLD}{'─'*60}{RESET}")
    if dry_run:
        print(f"{YELLOW}{BOLD}  DRY RUN complete — nothing was deleted.{RESET}")
        print(f"  Would remove : {RED}{len(all_remove)}{RESET} entries")
    else:
        print(f"{GREEN}{BOLD}  Cleanup complete.{RESET}")
        print(f"  Deleted : {RED}{deleted}{RESET} entries"
              + (f"  {RED}  Failed: {failed}{RESET}" if failed else ""))
    print(f"  Kept    : {GREEN}{len(all_keep)}{RESET} entries")
    if all_ignored:
        print(f"  Ignored : {DIM}{len(all_ignored)}{RESET} entries (config)")
    if delete_unknown:
        if dry_run:
            print(f"  Would remove (unknown) : {RED}{len(all_unknown)}{RESET} entries")
        else:
            print(f"  Deleted (unknown) : {RED}{deleted_unknown}{RESET} entries"
                  + (f"  {RED}  Failed: {failed_unknown}{RESET}" if failed_unknown else ""))
    else:
        print(f"  Unknown : {YELLOW}{len(all_unknown)}{RESET} entries (kept, review manually)")
    print(f"{CYAN}{BOLD}{'─'*60}{RESET}\n")

    # ── Discord ──────────────────────────────────────────────────────────────
    discord_cfg = cfg.get("discord", {})
    webhook     = discord_cfg.get("webhook_url", "")
    notify_dry  = discord_cfg.get("notify_on_dry_run", True)

    if webhook and (not dry_run or notify_dry):
        send_discord(webhook, dry_run, delete_unknown, per_dir, all_remove, all_unknown)


if __name__ == "__main__":
    main()
